// Description: This script is used to remove the files that are generated by the fetch_data.js script.

// Import the fs module
import fs from 'fs'; 

// List of files to remove
const filesToRemove = ['successful_data.json', 'fetch_log.txt', 'failed_data.json'];

// Function to remove files
const removeFiles = () => {
    // Loop through the filesToRemove array
    filesToRemove.forEach(filename => {
        // Try to remove the file
        try {
            // Remove the file
            fs.unlinkSync(filename);
            // Log a success message
            console.log(`${filename} has been removed successfully.`);
        // Catch any errors
        } catch (err) {
            // Log an error message
            console.error(`Error removing ${filename}:`, err);
        }
    });
};

// Call the function to remove files
removeFiles();
